### PR TITLE
Revert unneeded project properties

### PR DESCRIPTION
**Pull request by rickykaare**

### CODE REVIEW

**Comment by davidkallesen** [comment]
@rickykaare Have you check that "dotnet pack" generate the correct version - hard to see on diffs?

**Comment by rickykaare** [comment]
Yes. The only fix we needed was the added package references

**Comment by perkops** [comment]
How about the internals of the nuget package itself? And the validations you can see via Nuget Explorer?
We copied the existing setup from egil, which spent alot of time getting those right.. would hate to see that "broken" again...

**Comment by rickykaare** [comment]
Fair enough. Just looked like a lot of left-overs from the build fix, that was not well-considered.

We might consider, not having duplicate ` <DebugType>embedded</DebugType>` properties defined.

**Comment by davidkallesen** [comment]
I aggree on no dublicates :-)

**Comment by perkops** [comment]
> Fair enough. Just looked like a lot of left-overs from the build fix, that was not well-considered.
> 
> We might consider, not having duplicate ` <DebugType>embedded</DebugType>` properties defined.

Well, just curious as to if it worked without :-) - I agree we should not have duplicate properties defined.

**Comment by rickykaare** [comment]
I got the same result in Nuget Explorer on both my local build from this branch and the latest in the nuget.org feed. So I assume there is no effect.

But on both it claims:
* Missing symbols
* Non deterministic
* Missing compiler flags

**Comment by perkops** [comment]
> I got the same result in Nuget Explorer on both my local build from this branch and the latest in the nuget.org feed. So I assume there is no effect.
> 
> But on both it claims:
> 
> * Missing symbols
> * Non deterministic
> * Missing compiler flags

Hmm, that sucks then :-/.. but I guess we have a cleanup job across our repos/setups - to remove unneeded properties then.

**Pull request closed without merging**
